version: '3.7'
services:
  KileraBot: 
    build: 
      context: './'
      dockerfile: Dockerfile
      args:
        - BUILD_NO_CACHE=${BUILD_NO_CACHE}
    image: bot:1.2.0
    container_name: KileraBot
    volumes:
      - ./your_bot_code:/app
    networks:
      - network
    restart: always

  MongoDB:
    image: mongo:latest
    container_name: MongoOtKilera
    ports: 
     - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - network

networks:
  network:
    driver: bridge
volumes:
  mongo-data: